# Generated by Django 2.1.7 on 2019-02-18 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='DislikeModel',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='LikeModel',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='VideoModel',
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='dislikemodel',
            options={'verbose_name': 'Dislike', 'verbose_name_plural': 'Dislikes'},
        ),
        migrations.AlterModelOptions(
            name='likemodel',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
