# Generated by Django 2.1.7 on 2019-02-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190218_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
