# Generated by Django 2.1.7 on 2019-02-19 10:50

from django.db import migrations, models
import videos.models.utils
import videos.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20190218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='generated_link',
            field=models.CharField(blank=True, default='', editable=False, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(upload_to=videos.models.utils.update_filename, validators=[videos.models.validators.validate_file_extension]),
        ),
    ]
