# Generated by Django 2.1.7 on 2019-02-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0006_auto_20190219_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_related_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
