# Generated by Django 2.1.7 on 2019-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videomodel_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
